spring:
  application:
    name: EventClean
  datasource:
#    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?ssl=false
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#    driver-class-name: org.postgresql.Driver
    url: jdbc:h2:mem:${H2_DB}
    username: ${H2_USER}
    password: ${H2_PASSWORD}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true